#include"main.h"
#include<stdio.h>

/**
*main-checkthecode
*
*Return:Always0.
*/
intmain(void)
{
chars[]="ROT13(\"rotateby13places\",sometimeshyphenatedROT-13)isasimplelettersubstitutioncipher.\n";
char*p;

p=rot13(s);
printf("%s",p);
printf("------------------------------------\n");
printf("%s",s);
printf("------------------------------------\n");
p=rot13(s);
printf("%s",p);
printf("------------------------------------\n");
printf("%s",s);
printf("------------------------------------\n");
p=rot13(s);
printf("%s",p);
printf("------------------------------------\n");
printf("%s",s);
return(0);
}
