#include"main.h"
#include<stdio.h>

/**
*main-checkthecode
*
*Return:Always0.
*/
intmain(void)
{
intnb;

nb=_atoi("98");
printf("%d\n",nb);
nb=_atoi("-402");
printf("%d\n",nb);
nb=_atoi("------++++++-----+++++--98");
printf("%d\n",nb);
nb=_atoi("214748364");
printf("%d\n",nb);
nb=_atoi("0");
printf("%d\n",nb);
nb=_atoi("Suite402");
printf("%d\n",nb);
nb=_atoi("++--98BatteryStreet;SanFrancisco,CA94111-USA");
printf("%d\n",nb);
nb=_atoi("---++++-++Sui-te-402#cisfun:)");
printf("%d\n",nb);
return(0);
}
