#include"3-calc.h"

intop_add(inta,intb);
intop_sub(inta,intb);
intop_mul(inta,intb);
intop_div(inta,intb);
intop_mod(inta,intb);

/**
*op_add-Returnsthesumoftwonumbers.
*@a:Thefirstnumber.
*@b:Thesecondnumber.
*
*Return:Thesumofaandb.
*/
intop_add(inta,intb)
{
return(a+b);
}
/**
*op_sub-Returnsthedifferenceoftwonumbers.
*@a:Thefirstnumber.
*@b:Thesecondnumber.
*
*Return:Thedifferenceofaandb.
*/
intop_sub(inta,intb)
{
return(a-b);
}
/**
*op_mul-Returnstheproductoftwonumbers.
*@a:Thefirstnumber.
*@b:Thesecondnumber.
*
*Return:Theproductofaandb.
*/
intop_mul(inta,intb)
{
return(a*b);
}
/**
*op_div-Returnsthedivisionoftwonumbers.
*@a:Thefirstnumber.
*@b:Thesecondnumber.
*
*Return:Thequotientofaandb.
*/
intop_div(inta,intb)
{
return(a/b);
}
/**
*op_mod-Returnstheremainderofthedivisionoftwonumbers.
*@a:Thefirstnumber.
*@b:Thesecondnumber.
*
*Return:Theremainderofthedivisionofabyb.
*/
intop_mod(inta,intb)
{
return(a%b);
}
